name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          cp laradock/.env.example laradock/.env
          docker-compose -f laradock/docker-compose.yml up -d nginx mysql workspace
          docker-compose exec workspace bash
          php artisan key:generate
