name: Laravel CI with LaraDock

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Laradock containers
      run: |
        cd laradock
        cp env-example .env
        docker-compose up -d nginx mysql redis workspace

    - name: Build Docker image
      run: |
        cd laradock
        docker-compose exec workspace bash -c "cd /var/www && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan key:generate"

    - name: Stop Laradock containers
      run: |
        cd laradock
        docker-compose stop
