name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          cd laradock
          cp .env.example .env
          docker-compose up -d nginx mysql workspace
          docker-compose exec workspace bash -c "cd /var/www && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan key:generate"
          
