name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Copy Laradock .env
        run: |
          cd ../laradock
          cp .env.example .env
          
      - name: Start Laradock containers
        run: |
          cd ../laradock
          docker compose up -d nginx mysql
          
      - name: Configure Laravel environment
        run: |
          cd ../laradock
          docker compose exec workspace bash -c '
            cd TodoApi
            cp .env.example .env
            php artisan key:generate
          '
          
      - name: Install Composer dependencies
        run: |
          cd ../laradock
          docker compose exec workspace -c '
            cd TodoApi
            composer install --no-interaction --prefer-dist --no-dev
          '
