name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Laradock services
        run: |
          cd laradock
          docker-compose up -d nginx mysql

      - name: Run database migrations
        run: |
          cd laradock
          cp .env.example .env
          docker-compose exec workspace php artisan migrate --seed

      - name: Stop Laradock services
        run: |
          cd laradock
          docker-compose down
