name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Copy Laradock .env
        run: |
          cd ../laradock
          cp .env.example .env
          
      - name: Start Laradock containers
        run: |
          cd ../laradock
          docker compose up -d nginx mysql
          
      - name: Configure Laravel environment
        run: |
          cd ../laradock
          docker compose exec workspace bash -c '
            cd TodoApi
            cp .env.example .env
            chown test_deploy:test_deploy .env
          '
          
      - name: Install Composer dependencies
        run: |
          cd ../laradock
          docker compose exec workspace bash -c '
            cd TodoApi
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          '
          chown -R test_deploy:test_deploy TodoApi/vendor
          
      - name: Generate key
        run: |
          cd ../laradock
          docker compose exec workspace bash -c '
            cd TodoApi
            php artisan key:generate
          '
          
      - name: Create Testing Database
        run: |
          cd ../laradock
          docker compose exec workspace bash -c '
            cd TodoApi
            mkdir -p database
            touch database/database.sqlite
          '
          
      - name: Migrate Testing database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          cd ../laradock
          docker compose exec workspace bash -c '
            cd TodoApi
            php artisan migrate --force
          '

  test:
      runs-on: self-hosted

      needs: build

      steps:
        - name: test
          run: |
            cd ../laradock
            docker compose exec workspace bash -c '
              cd TodoApi
              php artisan test
            '

          
          
          
