name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: PWD
        run: pwd
        
      - name: Start Laradock containers
        run: |
          cd ../laradock
          pwd
          docker compose up -d nginx mysql
          
      - name: Configure Laravel environment
        run: |
          cp ../laradock/env-example ../laradock/.env
          cd ../laradock
          pwd
          docker compose exec workspace php artisan key:generate
